# Please refer https://docs.docker.com/compose to learn more about Docker Compose.
version: '3.4'

networks: 

    DevelopmentNetwork:
        driver: bridge

services:

    # Bring up the latest SQL Server
    sql:
        container_name: sql2019-composed
        image: mcr.microsoft.com/mssql/server:latest
        ports:
            - 1433:1433
        volumes:
            - C:\SQL\Data:/sqldata
            - C:\SQL\SystemDbs:/var/opt/mssql/data
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=letme!n123
            - MSSQL_DATA_DIR=/sqldata
            - MSSQL_LOG_DIR=/sqldata
        networks:
            - DevelopmentNetwork
            
    # Bring up the latest redis container
    redis:
        container_name: redis
        image: redis:latest
        ports:
            - 9000:6379
        networks:
            - DevelopmentNetwork
            
    # This is a web-based redis management tool. Access it on localhost:8081
    redis-commander:
        container_name: redis-commander
        image: rediscommander/redis-commander
        environment: 
            - REDIS_HOSTS=local:redis:6379
        ports:
            - 8081:8081
        depends_on: 
            - redis
        networks:
            - DevelopmentNetwork
